version: '2'
services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - '9292:9292'
    command: rackup --host 0.0.0.0 

  sidekiq:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    command: bundle exec sidekiq -r ./capo.rb

  redis:
    image: 'redis'
