version: '2'
services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - '9292:80'
    command: rackup --host 0.0.0.0 --port 80

  redis:
    image: 'redis'
